language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yichen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yichen/react-test npm test

after_success: 
  - docker build -t yichen/multi-client ./client 
  - docker build -t yichen/multi-nginx ./nginx
  - docker build -t yichen/multi-server ./server
  - docker build -t yichen/multi-worker ./worker
# Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" docker login -u "$DOCKER_ID" --password-stdin
# Push above images to Docker hub
  - docker push yichen/multi-client
  - docker push yichen/multi-nginx
  - docker push yichen/multi-server
  - docker push yichen/multi-worker