language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wyc910717/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wyc910717/react-test npm test

after_success: 
  - docker build -t wyc910717/multi-client ./client 
  - docker build -t wyc910717/multi-nginx ./nginx
  - docker build -t wyc910717/multi-server ./server
  - docker build -t wyc910717/multi-worker ./worker
# Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push above images to Docker hub
  - docker push wyc910717/multi-client
  - docker push wyc910717/multi-nginx
  - docker push wyc910717/multi-server
  - docker push wyc910717/multi-worker